// ...existing code...
import ConfirmEmailPage from './routes/confirm-email';

export const routes = [
  // ...existing routes...
  {
    path: '/confirm-email',
    element: <ConfirmEmailPage />,
  },
  // ...existing routes...
];
// ...existing code...
