package com.example.courtierprobackend.documents.datalayer.enums;

public enum StageEnum {
    BUYER_PREQUALIFY_FINANCIALLY,
    BUYER_SHOP_FOR_PROPERTY,
    BUYER_SUBMIT_OFFER,
    BUYER_OFFER_ACCEPTED,
    BUYER_HOME_INSPECTION,
    BUYER_FINANCING_FINALIZED,
    BUYER_FIRST_NOTARY_APPOINTMENT,
    BUYER_SECOND_NOTARY_APPOINTMENT,
    BUYER_OCCUPANCY,
    BUYER_TERMINATED,
    SELLER_INITIAL_CONSULTATION,
    SELLER_LISTING_PUBLISHED,
    SELLER_REVIEW_OFFERS,
    SELLER_ACCEPT_BEST_OFFER,
    SELLER_CONDITIONS_MET,
    SELLER_NOTARY_COORDINATION,
    SELLER_NOTARY_APPOINTMENT,
    SELLER_HANDOVER_KEYS,
    SELLER_TERMINATED
}
