package com.example.courtierprobackend.documents.datalayer.enums;

public enum StageEnum {
    BUYER_FINANCIAL_PREPARATION,
    BUYER_PROPERTY_SEARCH,
    BUYER_OFFER_AND_NEGOTIATION,
    BUYER_FINANCING_AND_CONDITIONS,
    BUYER_NOTARY_AND_SIGNING,
    BUYER_POSSESSION,
    SELLER_INITIAL_CONSULTATION,
    SELLER_PUBLISH_LISTING,
    SELLER_OFFER_AND_NEGOTIATION,
    SELLER_FINANCING_AND_CONDITIONS,
    SELLER_NOTARY_AND_SIGNING,
    SELLER_HANDOVER
}
