package com.example.courtierprobackend.transactions.datalayer.enums;

public enum SellerStage {
    SELLER_INITIAL_CONSULTATION,
    SELLER_LISTING_PUBLISHED,
    SELLER_REVIEW_OFFERS,
    SELLER_ACCEPT_BEST_OFFER,
    SELLER_CONDITIONS_MET,
    SELLER_NOTARY_COORDINATION,
    SELLER_NOTARY_APPOINTMENT,
    SELLER_HANDOVER_KEYS,
    SELLER_TERMINATED
}
