package com.example.courtierprobackend.audit.timeline_audit.dataaccesslayer.Enum;

public enum TimelineEntryType {
    CREATED,
    STAGE_CHANGE,
    NOTE,
    TRANSACTION_NOTE,
    DOCUMENT_REQUESTED,
    DOCUMENT_REQUEST_UPDATED,
    DOCUMENT_SUBMITTED,
    DOCUMENT_APPROVED,
    DOCUMENT_NEEDS_REVISION,
    STATUS_CHANGE,
    PROPERTY_ADDED,
    PROPERTY_UPDATED,
    PROPERTY_REMOVED,
    OFFER_RECEIVED,
    OFFER_UPDATED,
    OFFER_REMOVED,
    PROPERTY_OFFER_MADE,
    PROPERTY_OFFER_UPDATED,
    OFFER_DOCUMENT_UPLOADED,
    CONDITION_ADDED,
    CONDITION_UPDATED,
    CONDITION_REMOVED,
    CONDITION_SATISFIED,
    CONDITION_FAILED
}

